# Julia and Documenter stuff
sudo: required
language: julia
services: docker
julia:
  - 1.1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email:
    recipients:
      - soodarnav01@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
# Docs stuff
jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

# Deployment stuff 
before_deploy:
- export TRAVIS_TAG=${TRAVIS_TAG:-dev}
- git tag $TRAVIS_TAG --force
# tex stuff
- docker pull dxjoke/tectonic-docker
- docker run --mount src=$TRAVIS_BUILD_DIR/docs/tex,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "./generate_tex.sh"
# weave stuff (don't know why the docker login is required; ppl have filed git issues about this)
- docker pull quantecon/julia-weave
- docker run -it --rm -v "$TRAVIS_BUILD_DIR/docs/notebooks":/usr/myapp -w /usr/myapp quantecon/julia-weave julia generate_notebooks.jl
deploy:
  provider: releases
  api_key: $GIT_KEY
  file_glob: true 
  file: 
  - $TRAVIS_BUILD_DIR/docs/tex/*.pdf
  - $TRAVIS_BUILD_DIR/docs/notebooks/*.ipynb
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
