name = "SimpleDifferentialOperators"
uuid = "7ccca996-40d6-5c2f-be7f-4eb2934af9c4"
version = "0.2.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DualNumbers = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
PATHSolver = "f5f7c340-0bb3-5c69-969a-41884d311d1b"

[targets]
test = ["Test", "DualNumbers", "BenchmarkTools", "PATHSolver"]
