name = "SimpleDifferentialOperators"
uuid = "7ccca996-40d6-5c2f-be7f-4eb2934af9c4"
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
DualNumbers = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"

[targets]
test = ["Test", "DualNumbers"]
